version: "3"

services:
  web:
    build: web
    ports:
    - 80
  db:
    build: db
  words:
    build: words
    ports:
    - 8080
  notebook:
    image: jupyter/datascience-notebook
    ports:
      - 8888:8888
    volumes:
       - ./data:/home/jovyan/work/data
      