version: "3"

services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474 
      - 7687:7687
    volumes:
      - ./Neo4j:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=none
  notebook:
    build: notebook/
    ports:
      - 8888:8888
    volumes:
       - ./:/home/jovyan/work/data
    environment:
      - GRANT_SUDO=yes
      